In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('placement.csv')
df.head()

   cgpa  package
0  6.89     3.26
1  5.12     1.98
2  7.82     3.25
3  7.42     3.67
4  6.94     3.57

In [18]:
class LR:
  def __init__(self):
    self.m = None
    self.b = None

  def fit(self, X_train, Y_train):
    num = 0
    den = 0
    # Get scalar means for X_train and Y_train
    X_mean = X_train.mean().values[0]
    Y_mean = Y_train.mean()

    for i in range(X_train.shape[0]):
      # Access scalar values for X_train and Y_train by integer location
      X_val = X_train.iloc[i].values[0]
      Y_val = Y_train.iloc[i]

      num = num + ((X_val - X_mean) * (Y_val - Y_mean))
      den = den + ((X_val - X_mean) * (X_val - X_mean))

    self.m = num / den
    self.b = Y_mean - (self.m * X_mean)
    print(self.m)
    print(self.b)

  def predict(self, X_test):
    print(self.m * X_test + self.b)

In [19]:
X = df.iloc[:,0:1]
Y = df.iloc[:,-1]

In [20]:
X

     cgpa
0    6.89
1    5.12
2    7.82
3    7.42
4    6.94
..    ...
195  6.93
196  5.89
197  7.21
198  7.63
199  6.22

[200 rows x 1 columns]

In [21]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, random_state=2)

In [22]:
lr = LR()

In [24]:
lr.fit(X_train,Y_train)

0.5579519734250721
-0.8961119222429152

In [25]:
lr.predict(X_test)

         cgpa
112  3.891116
29   3.093245
182  2.384646
199  2.574349
193  1.653729
85   1.776478
10   2.072193
54   2.931439
115  3.762787
35   2.937018
12   4.091979
92   3.511709
13   2.970495
126  2.401384
174  3.188097
2    3.467073
44   1.943864
3    3.243892
113  2.976075
14   3.416857
23   2.557611
25   3.165778
6    2.858905
134  3.121142
165  3.684674
173  2.870064
45   3.494970
65   3.344323
48   3.919014
122  1.960602
178  3.651197
64   3.210415
9    3.740469
57   2.786371
78   2.780792
71   3.271789
128  3.528447
176  2.613406
131  2.658042
53   2.713837